### PR TITLE
Update

### PR DESCRIPTION
**Pull request by andreaskurth**
I need to share our Style Guide with partners for a project, but I noticed that it is outdated.

Here is an update to align with the settled points of the internal document. Additionally, I suggest we
- [remove commit emojis](https://github.com/pulp-platform/style-guidelines/commit/ae0e8833b99bf6020844fc3839be02074de01100) with the rationale that they are an a exotic outlier compared to the minimal/sober points the rest of the style guide establishes. They are not forbidden and can still be encouraged on a per-project basis if the owner prefers them.
- [make the essential TLDR items bold](https://github.com/pulp-platform/style-guidelines/commit/92ffbaf166bee0d11185a70a4fe9c7002d29001d) so that they immediately scream at the reader.

### CODE REVIEW

**Review by zarubaf — APPROVED** [review]
LGTM. Maybe you can also include the discussion we had about `!` vs `~`, `&&` vs `&` then it is good to go from my side. Thanks for taking the time and updating.

**Review by msfschaffner — APPROVED** [review]
LGTM, thanks for updating!

**Comment by zarubaf** [comment]
Feel free to merge this PR yourself.

**Comment by andreaskurth** [comment]
Thanks for your reviews.

I have added the [rule on logical vs. bitwise binary operators](https://github.com/pulp-platform/style-guidelines/pull/3/commits/43ca3533ccdde4e75cd4c2a3eabd65663a1372d2) you mentioned, a related [rule on evaluating single-bit signals](https://github.com/pulp-platform/style-guidelines/pull/3/commits/e4048cf98ed5e30e8c0266a58c6c07117431c85a), and one rule each for [clocks](https://github.com/pulp-platform/style-guidelines/pull/3/commits/67e2997580ab49a731899ad23822512c3eb64dd8) and [resets](https://github.com/pulp-platform/style-guidelines/pull/3/commits/8e594303debebe5d177a25e37b5800b26e3f3e93) (both taken from the document).

If you agree @zarubaf, I will merge the PR.

I suggest we tag the resulting revision as v1.0.0. There is no need for a release announcement or anything like that, but for sharing it is useful to have a stable identifier that is not composed of hex characters.

**Comment by zarubaf** [comment]
Go ahead. I agree on the revision number.

**Pull request merged**
